import type { NextPage } from 'next';
import Link from 'next/link';
import Head from 'next/head';
import { trpc } from '../utils/trpc';
import { useSession } from 'next-auth/react';

const Home: NextPage = () => {
  const hello = trpc.useQuery(['example.hello', { text: 'from tRPC' }]);
  const { data: session, status } = useSession();

  return (
    <>
      <Head>
        <title>FitDetector</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='container mx-auto flex flex-col items-center justify-center min-h-screen p-4'>
        <h1 className='text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700'>
          <span className='text-purple-300'>Fit</span>Detector
        </h1>
        <div className='p-3 text-2xl text-blue-500 flex justify-center items-center w-full'>
          {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
        </div>
        <div className='p-3 text-2xl text-blue-500 flex justify-center items-center w-full'>
          Your Authentication Status: {status}
        </div>
        {status === 'unauthenticated' && (
          <Link href='/api/auth/signin'>
            <a className='m-3 bg-transparent hover:bg-blue-500 text-blue-500 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded'>
              Sign In
            </a>
          </Link>
        )}
        {status === 'authenticated' && (
          <Link href='/api/auth/signout'>
            <a className='m-3 bg-transparent hover:bg-red-500 text-red-500 font-semibold hover:text-white py-2 px-4 border border-red-500 hover:border-transparent rounded'>
              Sign Out
            </a>
          </Link>
        )}
      </main>
    </>
  );
};

export default Home;
